### ISSUE TITLE
ZeroSSL changes

### ISSUE THREAD

**Issue by objectdatastorage** [ReinerNippes/nextcloud#118]
It appears ZeroSSL has made changes and requires an email address to be registered. Please can you recommend a temporary or permanent fix. We are using the nextcloud-reloaded with Ubuntu.

`  TASK [tls-certificate : get certificates] **************************************
Monday 14 June 2021  18:52:43 +0000 (0:00:00.418)       0:00:55.981 *********** 
fatal: [localhost]: FAILED! => changed=true 
  cmd:
  - ./acme.sh
  - --issue
  - --home
  - /opt/acme/sh
  - --config-home
  - /opt/acme/sh/conf
  - --domain
  - test1943.objectivedatastorage.com
  - --keylength
  - ec-256
  - --cert-home
  - /opt/acme/sh/certs
  - --cert-file
  - /etc/ssl/private/test1943.objectivedatastorage.com/test1943.objectivedatastorage.com.crt
  - --keylength
  - ec-256
  - --cert-home
  - /opt/acme/sh/certs
  - --cert-file
  - /etc/ssl/private/test1943.objectivedatastorage.com/test1943.objectivedatastorage.com.crt
  - --key-file
  - /etc/ssl/private/test1943.objectivedatastorage.com/test1943.objectivedatastorage.com.key
  - --ca-file
  - /etc/ssl/private/test1943.objectivedatastorage.com/ca.crt
  - --fullchain-file
  - /etc/ssl/private/test1943.objectivedatastorage.com/fullchain.crt
  - --webroot
  - /var/www/letsencrypt
  - --reloadcmd
  - systemctl restart nginx
  delta: '0:00:00.550492'
  end: '2021-06-14 18:52:44.005657'
  failed_when_result: true
  msg: non-zero return code
  rc: 1
  start: '2021-06-14 18:52:43.455165'
  stderr: |-
    [Mon Jun 14 18:52:44 UTC 2021] Please add '--debug' or '--log' to check more details.
    [Mon Jun 14 18:52:44 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
  stderr_lines: <omitted>
  stdout: |-
    [Mon Jun 14 18:52:43 UTC 2021] Using CA: https://acme.zerossl.com/v2/DV90
    [Mon Jun 14 18:52:43 UTC 2021] Create account key ok.
    [Mon Jun 14 18:52:43 UTC 2021] No EAB credentials found for ZeroSSL, let's get one
    [Mon Jun 14 18:52:43 UTC 2021] acme.sh is using ZeroSSL as default CA now.
    [Mon Jun 14 18:52:43 UTC 2021] Please update your account with an email address first.
    [Mon Jun 14 18:52:43 UTC 2021] acme.sh --register-account -m my@example.com
    [Mon Jun 14 18:52:44 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
  stdout_lines: <omitted>`

**Comment by objectivedatastorage** [comment]
I have got this working again by setting --server letsencrypt when running ./acme.sh --issue

**Comment by ReinerNippes** [comment]
should be fixed now. with commit a61466848fce0351bd7d031d8bc917c062dd2167
