### ISSUE TITLE
SSL error: connection not secure

### ISSUE THREAD

**Issue by 2002-db8** [ReinerNippes/nextcloud#13]
/var/log/nginx/nginx.error.log

[crit] 30807#30807: *27 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 74.82.47.4, server: 0.0.0.0:443

Not sure where to find the ansible run log?

**Comment by ReinerNippes** [comment]
Does this article match your problem?
https://serverfault.com/questions/905011/nginx-ssl-do-handshake-failed-ssl-error1417d18cssl

The ssl cipher of nginx can be adjusted here:
https://github.com/ReinerNippes/nextcloud/blob/master/roles/prep_nginx/templates/ssl.conf.selfsigned.j2

**Comment by 2002-db8** [comment]
I found that too, though no solutions. After looking for an hour I just installed certbot, python-certbot-nginx and moved the letscrypt.conf. Did certbot --nginx.

Worked as a charm. Thanks for your comment.

Ubuntu 18.04.1 btw.
