### ISSUE TITLE
Ansible script fails to install / No action detected

### ISSUE THREAD

**Issue by Dracoform** [ReinerNippes/nextcloud#18]
Unfortunatly I had problems using the script on Debian 9.5.
Since I never used ansible before, I was at a loss on how to solve it myself, however maybe its a simple fix or just a "work in progress"

When running the playbook I get

> root@nexcloudserver:~/nextcloud# ansible-playbook nextcloud.yml
> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/root/nextcloud/roles/prep_os/tasks/main.yml': line 4, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
> - name: include os specific tasks
>   ^ here
> 

If I comment out the offending lines it ends with a 

> ERROR! The field 'loop' is supposed to be a string type, however the incoming data structure is a <class 'ansible.parsing.yaml.objects.AnsibleSequence'>
> 
> The error appears to have been in '/root/nextcloud/roles/prep_os/tasks/main.yml': line 85, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
> - name: change ImageMagick settings
>   ^ here
>

**Comment by ReinerNippes** [comment]
I guess you use an older version of ansible. which version are you using? -> ansible --version

btw: I corrected the prepare_system.sh script. maybe it did run well on your system.
