### ISSUE TITLE
transparent hugepages

### ISSUE THREAD

**Issue by ggeorgg** [ReinerNippes/nextcloud#23]
Hi,
I have tried the playbook on my Ubuntu and I get this warning when I play it the first time:
![grafik](https://user-images.githubusercontent.com/13244552/52904582-3d4f4380-322e-11e9-8094-cac55e649816.png)
I guess something like mentioned on [https://stackoverflow.com/questions/44800633/how-to-disable-transparent-huge-pages-thp-in-ubuntu-16-04lts](https://stackoverflow.com/questions/44800633/how-to-disable-transparent-huge-pages-thp-in-ubuntu-16-04lts) is needed instead?

**Comment by ReinerNippes** [comment]
Hi,
the warning can be ignored save. The huge pages are disabled. Permanent. 
It's an Ansible feature to warn if you install an init script on a systemd machine. Although it's working.
Maybe in the future I'll use https://github.com/GekoCloud/ansible-role-disable-thp
