### ISSUE TITLE
postgresql/docker performace

### ISSUE THREAD

**Issue by serazoli** [ReinerNippes/nextcloud#26]
Hi
I don't understand exactly why you use docker to run postgresql and why set up the nextcloud that connect through network to postgresql.
In my tests the docker-proxy process use approx. 10% cpu (2vcpu 4gb ram) whit this setup.
If nexcloud connect to postgresql through unix socket then this docker-network ovweload disappear.
I propose that you setup postgersql that run without docker or at least nexloud connect throught unix socket.
Sorry for my bad english

**Comment by ReinerNippes** [comment]
> I don't understand exactly
The first version of this playbook where mariadb only. (without docker)
The time I implemented postgres I also learned docker and so I implemented postgres as a container. In fact I should change it because I have also a docker only version of the playbooks. 

> at least nexloud connect throught unix socket
do you have a link to a config example?

**Comment by serazoli** [comment]
Sorry i don't keep it my modifications. :( 
(I thought that notice here that this is not the optimal solution)
Maybe you should add `- "/var/run/postgresql:/var/run/postgresql:rw"` to `roles/prep_postgres/tasks/main.yml` to line 57 and `--database-host` should be empty string in `first setup nexctcloud` task

**Comment by ReinerNippes** [comment]
Was a bit more work since the variable {{ nc_db_host }} is also used to control if the role prepare_postgres is executed in nextcloud.yml.   

I create a new branch. You want to test? 
https://github.com/ReinerNippes/nextcloud/tree/postgres.socket

Ane I'm not sure if the mode 0777 for /var/run/porstgres isn't a security issue.

**Comment by serazoli** [comment]
I think that 755 is enough.
I would suggest that if you work around the postgresql then remove the docker version and install natively.
I hope that i will have a little free time and take a test with the new version (with native postgres)

**Comment by ReinerNippes** [comment]
Hi, there is a new version in the postgres.socket branch ready for testing.

**Comment by serazoli** [comment]
I made quick test and mostly works well. When I run an `occ files:scan --all` then I got an error. It was problem with `bigint` so i run the `occ db:convert-filecache-bigint` command and after that was OK.
thx

**Comment by ReinerNippes** [comment]
the missing db:convert-filecache-bigint should be fixed as well.
https://github.com/ReinerNippes/nextcloud/blob/postgres.socket/roles/prep_nextcloud/tasks/main.yml#L115

**Comment by serazoli** [comment]
fortunately i don't close my workstation and i can check the playbook logs. Here the relevant part:
```
TASK [prep_nextcloud : convert filecache bigint] ****************************************************************************************************************************************************************
Wednesday 20 February 2019  15:26:24 +0200 (0:00:01.924)       0:05:02.469 ****                                                                                                                                  
changed: [*********************] => changed=true                                                                                                                                                                    
  cmd: sudo -u www-data php occ db:convert-filecache-bigint                                                                                                                                                      
  delta: '0:00:02.033931'                                                                                                                                                                                        
  end: '2019-02-20 14:26:28.113114'                                                                                                                                                                              
  rc: 0                                                                                                                                                                                                          
  start: '2019-02-20 14:26:26.079183'                                                                                                                                                                            
  stderr: ''                                                                                                                                                                                                     
  stderr_lines: []                                                                                                                                                                                               
  stdout: |-                                                                                                                                                                                                     
    Nextcloud or one of the apps require upgrade - only a limited number of commands are available                                                                                                               
    You may use your browser or the occ upgrade command to do the upgrade
    Following columns will be updated:
  
    * filecache.mtime
    * filecache.storage_mtime
  
    This can take up to hours, depending on the number of files in your instance!
  stdout_lines: <omitted>
```
Maybe have bug in nextcloud(?!)

**Comment by ReinerNippes** [comment]
maybe i have to change the execution order of 

https://github.com/ReinerNippes/nextcloud/blob/postgres.socket/roles/prep_nextcloud/tasks/main.yml#L115
and
https://github.com/ReinerNippes/nextcloud/blob/postgres.socket/roles/prep_nextcloud/tasks/main.yml#L125

i'll check.

**Comment by vkuehn** [comment]
any news on that ? Actually your docker installation removed my docker install and reinstalled it. I had the same problem and would appreciate a docker free installation fro numerous reasons...!?

**Comment by ReinerNippes** [comment]
i just tested the branch "flex.ports" on ubuntu and debian. worked without problem.

yes. the playbook replaces the ubuntu docker packages with packages from docker.com 
it seems that the docker packages are better maintained.
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
