### ISSUE TITLE
Remote install

### ISSUE THREAD

**Issue by serazoli** [ReinerNippes/nextcloud#27]
Hi,
When i change the `connection` to `ssh` in the `inventory` file that I can install nexcloud to a remote server then i also should modify/remove the `connection` in the `nextcloud.yml` (only_office.yml collabora.yml)
Maybe the `connection: local` is redundant in this file(s)
Sorry my bad english

**Comment by ReinerNippes** [comment]
Fixed.
https://github.com/ReinerNippes/nextcloud/commit/a4aac001dd3a69a63c3883d34709833595b5260d

**Comment by serazoli** [comment]
I think you should remove `connection: local` also from `only_office.yml` and `collabora.yml`
