### ISSUE TITLE
Collabora not working

### ISSUE THREAD

**Issue by ggeorgg** [ReinerNippes/nextcloud#28]
Hi Reiner, 
I am quite sure this is a configuration problem on my side, but I don't really know. 
I installed nextcloud with postgresql and chose to use letsencrypt with staging. I also set install_collabora=true.
Creating a collabora document is possible, in the web gui, but I can't open it: 
![grafik](https://user-images.githubusercontent.com/13244552/53020957-62bf9580-3458-11e9-9ceb-f503145dc7cb.png)

Every time I click the file to open it, I get two new errors in the nextcloud log: 

```
[PHP] Error: Cannot declare class GuzzleHttp\Handler\CurlFactory, because the name is already in use at /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php#15

```

```
[richdocuments] Error: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>

 0. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 149
    createRejection(GuzzleHttp\Handl ... l}, {errno: 60,error ... 4})

```

I already tried this [https://stackoverflow.com/a/49071524/10744485](https://stackoverflow.com/a/49071524/10744485) (adapted to ubuntu), but it didn't work. 

By the way, I would rather like to test it in my virtualbox with selfsigned certificates, but I can't get Collabora to work there either. Is this combination even possible with this ansible playbook?

Thank you very much for this great playbook!

**Comment by ReinerNippes** [comment]
>  letsencrypt with staging
there is already an open issue with selfsigned certificates and the office suites.
my understanding was (i didn't have time to dive deeper into the matter) that both office suites need a fullchained certificates. and right now the selfsigned certifcates created in the playbooks aren't.

**Comment by ReinerNippes** [comment]
the branch [nextcloud-reloaded](https://github.com/ReinerNippes/nextcloud/tree/nextcloud-reloaded) should work now with selfsigned certs. (at least the nginx version)
