### ISSUE TITLE
PHP module zip not installed

### ISSUE THREAD

**Issue by HenrikWMG** [ReinerNippes/nextcloud#29]
I got an error at:
TASK [prep_nextcloud : first setup nextcloud] 

________________________________________
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "sudo -u nginx php occ maintenance:install --database mysql --database-host localhost --database-name nextcloud --database-table-prefix nc_ --database-user nextcloud --database-pass HIDDEN_PADDWORD --admin-user admin --admin-pass HIDDEN_PADDWORD --data-dir /var/www/nextcloud/data", "delta": "0:00:00.702615", "end": "2019-04-15 15:05:04.374868", "msg": "non-zero return code", "rc": 1, "start": "2019-04-15 15:05:03.672253", "stderr": "", "stderr_lines": [], "stdout": "PHP module zip not installed.\nPlease ask your server administrator to install the module.\n\nAn unhandled exception has been thrown:\nException: Environment not properly prepared. in /var/www/nextcloud/lib/private/Console/Application.php:166\nStack trace:\n#0 /var/www/nextcloud/console.php(95): OC\\Console\\Application->loadCommands(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')\n#2 {main}", "stdout_lines": ["PHP module zip not installed.", "Please ask your server administrator to install the module.", "", "An unhandled exception has been thrown:", "Exception: Environment not properly prepared. in /var/www/nextcloud/lib/private/Console/Application.php:166", "Stack trace:", "#0 /var/www/nextcloud/console.php(95): OC\\Console\\Application->loadCommands(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')", "#2 {main}"]}

In my case i installed "php72-php-pecl-zip" via "yum install php72-php-pecl-zip" This fixed the shown error

**Comment by ReinerNippes** [comment]
should be fixed now.
https://github.com/ReinerNippes/nextcloud/blob/flex.ports/roles/prep_php/tasks/CentOS.yml#L62
