### ISSUE TITLE
Renewal Let's Encrypt certificate

### ISSUE THREAD

**Issue by kingfisher77** [ReinerNippes/nextcloud#30]
Hi, we cannot find the renewal mechanism for the let's encrypt certificate. Do we miss something or should we add it manually?

**Comment by acs-ferreira** [comment]
https://certbot.eff.org/docs/using.html#renewing-certificates

**Comment by ReinerNippes** [comment]
it should be in /etc/cron.d/certbot

**Comment by kingfisher77** [comment]
Thank you for the explanation and your good work. Our thought was just that the playbook should just take care for the renewal already.

**Comment by ReinerNippes** [comment]
The playbook should get you a certificate. 
https://github.com/ReinerNippes/nextcloud/blob/0788b8e895124ad43342823cbce9391f3c75733b/roles/prep_letsencrypt/tasks/main.yml#L27
If the file cert.pem didn't exist.
https://github.com/ReinerNippes/nextcloud/blob/0788b8e895124ad43342823cbce9391f3c75733b/roles/prep_letsencrypt/tasks/main.yml#L29

Do you want me to add a "certbot renew"? IMHO that wouldn't be necessary.

On the machines where I'm testing the cron job to keep the certificate updated  is created during the installation of certbot. Didn't that happen on your machine?

**Comment by kingfisher77** [comment]
On my machines (i installed nextcloud on two machines with the playbook) there are no cron job established. I cannot find any ansible tasks for that either?

**Comment by kingfisher77** [comment]
From my point of view the renew task should be part of the playbook. It appears incomplete without.

**Comment by ReinerNippes** [comment]
OK. Of course you are right that the installation is incomplete without the automatic renewal. 

Which linux are you using? Which hoster (if any)?

On AWS EC2, Strato and Scaleway Ubuntu it's created in /etc/cron.d/certbot. So I assumed I have nothing to do more.

**Comment by kingfisher77** [comment]
We have CentOS7 on premise. We integrated your playbook into our ansible control server and adjusted everything accordingly (quite a lot like nfs-client config). We will integrate a renew task by ourselve. Did not know that Ubuntu on hosting machines creates cronjob for certbot automatically. Greetings!

**Comment by ReinerNippes** [comment]
And I thought if the cronjob is include in ones distro package it's included in all of them...

added a cronjob for centos.
https://github.com/ReinerNippes/nextcloud/blob/a7a7ebd50e5098060c51afda9873986beffb5520/roles/prep_letsencrypt/tasks/CentOS.yml#L14

**Comment by kingfisher77** [comment]
Thank you!

**Comment by raonyguimaraes** [comment]
Hi, can you please add automatic renewal for ubuntu as well?

**Comment by ReinerNippes** [comment]
On Ubuntu 18 (AWS) it's included in the letsencrypt package. -> /etc/cron.d/certbot

Which version of Ubuntu are you using?

To solve the issue for oyu just move the task in 

https://github.com/ReinerNippes/nextcloud/blob/a7a7ebd50e5098060c51afda9873986beffb5520/roles/prep_letsencrypt/tasks/CentOS.yml#L14

to the end of 'prep_letsencrypt/tasks/main.yml'. Then it's executed on all distros.
