### ISSUE TITLE
Add support for IPv6

### ISSUE THREAD

**Issue by acs-ferreira** [ReinerNippes/nextcloud#35]
So in nGinx template add `listen [::]:` for both 80 and 443 ports.
_(Maybe with some logic to detect if it is enabled on the server? - see https://github.com/juju4/ansible-ipv6)_

**Comment by ReinerNippes** [comment]
the logic to test if ipv6 is available should look like:

{% if ansible_default_ipv6.address is defined %}
listen [::]:
{% endif %} 

in the nextcloud.conf.j2 template file. 

could you try? i have right now no ipv6 machine at hand.

**Comment by acs-ferreira** [comment]
I'll give you feedback tomorrow, thanks! 👍

**Comment by acs-ferreira** [comment]
Seems good, thanks.
Not closing if you want to implement it.

**Comment by ReinerNippes** [comment]
I included it in the flex.port branch:

https://github.com/ReinerNippes/nextcloud/blob/d533c00e74f2db5cd3c26e48562221d4b73b637e/roles/prep_nginx/templates/nextcloud.conf.j2#L3
