### ISSUE TITLE
NC 16 and version option in inventory

### ISSUE THREAD

**Issue by skunkr** [ReinerNippes/nextcloud#36]
Hi,
Any planned updates for v16 soon ?
Also, any plans on choosing the version in the inventory ? This might be tricky, since NC16 has some mysql settings different than previous versions..
Thank you !

**Comment by ReinerNippes** [comment]
Try to edit the invetory file to get another version then latest.

https://github.com/ReinerNippes/nextcloud/blob/a7a7ebd50e5098060c51afda9873986beffb5520/inventory#L68

see also here:

https://help.nextcloud.com/t/time-for-some-testing-beta-1-of-nextcloud-16-is-here/50108/6?u=reiner_nippes

And maybe I should backport the config part of the playbook from the docker version.

https://github.com/ReinerNippes/nextcloud_on_docker/blob/e4a4ca22901e099fe3af51b3ce94fa9105b58929/roles/nextcloud_config/tasks/main.yml#L32 

or which db settings do you mean?

**Comment by skunkr** [comment]
Hi, I am refering about 4 bytes UTF8 settings that seems to be needed.

**Comment by ReinerNippes** [comment]
the mariadb my.cnf can be adjusted here

https://github.com/ReinerNippes/nextcloud/blob/a7a7ebd50e5098060c51afda9873986beffb5520/roles/prep_mariadb/templates/my.cnf.j2#L64

**Comment by skunkr** [comment]
Perfect ! Thank you very much !

**Comment by ReinerNippes** [comment]
and if that has to be added to confip.php (sudo -u www-data php occ config:system:set mysql.utf8mb4 --type boolean --value="true") that would go here:

https://github.com/ReinerNippes/nextcloud/blob/a7a7ebd50e5098060c51afda9873986beffb5520/roles/prep_nextcloud/defaults/main.yml#L4

i'm sure if it's necessary.
