### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by kingfisher77** [ReinerNippes/nextcloud#38]
Hallo, hat es einen Grund, warum nginx ohne

`add_header X-Frame-Options deny;`

konfiguriert ist?

**Comment by ReinerNippes** [comment]
Die Option ist nicht in der ["empfohlenen" Konfig von Nextcloud](https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html) enthalten.
Kann aber einfach hier https://github.com/ReinerNippes/nextcloud/blob/master/roles/prep_nginx/files/header.conf ergänzt werden. 
Ohne die Ergänzung bekomme ich bei https://securityheaders.com/ immer noch ein A+ und die Info das X-Frame-Options auf SAMEORIGINE gesetzt ist.
