### ISSUE TITLE
As the ansible playbook is idempotent, can I use it to fix a broken installation of nextcloud?

### ISSUE THREAD

**Issue by jcklpe** [ReinerNippes/nextcloud#41]
I'm having a lot of cascading failures with my installation of nextcloud. Poor choices on my part I'm sure. But I'm wondering if there's a way I can start over with this process and maybe revert my installation to a more "correct" and "clean" installation of nextcloud. 

Is that possible using this ansible playbook? 

Or perhaps I can do it by doing a manual update to 16.0.3?

**Comment by ReinerNippes** [comment]
If you have still the version you used to setup nextcloud: yes.
but nextcloud would not be installed again. only mysql/nginx/php/redis would be updated and the config would be setup to a working version. 

always do backups before you start touching your installation. ;-) 

if you do a `git fetch && git stash && git pull && git stash pop` (aka get the newest version of the playbook) it might be incompatible to your steup.

in this case i would advice to setup a new server and migrate the data from the old.

**Comment by jcklpe** [comment]
@ReinerNippes  Managed to get everything fixed! Thank you!
