### ISSUE TITLE
prep_postgres step fails

### ISSUE THREAD

**Issue by penyaringan** [ReinerNippes/nextcloud#42]
The prep_postgres step fails on Debian 9 because of this https://docs.ansible.com/ansible/latest/user_guide/become.html#becoming-an-unprivileged-user. 

A simple work-around is to add the following to nextcloud/ansible.cfg:
allow_world_readable_tmpfiles = True

TASK [prep_postgres : create nextcloud db] ************************************************************************************************************************************************************************
Wednesday 24 July 2019  01:03:11 +0000 (0:00:00.239)       0:02:39.458 ********
fatal: [localhost]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1563930191.91-232732494717003/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1563930191.91-232732494717003/AnsiballZ_postgresql_db.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

**Comment by ReinerNippes** [comment]
I usually run the playbook with sudo on debian systems.
