### ISSUE TITLE
Unable to enable service disable-transparent-huge-pages: Failed to execute operation: Too many levels of symbolic links

### ISSUE THREAD

**Issue by Netbulae** [ReinerNippes/nextcloud#45]
On CentOS 7.6, I get the following error.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to enable service disable-transparent-huge-pages: Failed to execute operation: Too many levels of symbolic links\n"}

I see the service gets linked
`- name: create link in /etc/systemd/system/
  file:
    src: /usr/local/src/disable-transparent-huge-pages.service
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    state: link`

But the RedHat/CentOS way is to link it put them into "/usr/lib/systemd/system/", when you enable the service another link gets put into "/etc/systemd/system/" to make it start

```
ln -s /usr/local/src/disable-transparent-huge-pages.service /usr/lib/systemd/system/

systemctl enable disable-transparent-huge-pages.service
```

> Created symlink from /etc/systemd/system/basic.target.wants/disable-transparent-huge-pages.service to /usr/local/src/disable-transparent-huge-pages.service.
> Created symlink from /etc/systemd/system/disable-transparent-huge-pages.service to /usr/local/src/disable-transparent-huge-pages.service.

**Comment by ReinerNippes** [comment]
should be fixed. 
https://github.com/ReinerNippes/nextcloud/commit/44b340cabbbf44b7cc0882bf7dd1133078ca67f3
