### ISSUE TITLE
Problems when running nextcloud.yml

### ISSUE THREAD

**Issue by boubouqc** [ReinerNippes/nextcloud#46]
./nextcloud.yml 
 [WARNING]:  * Failed to parse /home/../nextcloud/inventory with yaml plugin: Syntax Error while loading YAML.   did not find expected <document
start>  The error appears to be in '/home/../nextcloud/inventory': line 1, column 13, but may be elsewhere in the file depending on the exact syntax
problem.  The offending line appears to be:   [nextcloud] localhost ansible_connection=local             ^ here
 [WARNING]:  * Failed to parse /home/../nextcloud/inventory with ini plugin: host range must be begin:end or begin:end:step
 [WARNING]: Unable to parse /home/../nextcloud/inventory as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
 [WARNING]: Could not match supplied host pattern, ignoring: nextcloud

PLAY [install nextcloud] ********************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP **********************************************************************************************************************************************

Tuesday 20 August 2019  15:41:14 +0000 (0:00:00.138)       0:00:00.138 ******** 
===============================================================================

**Comment by sboulianne** [comment]
How can I fix it ?
Thanks.

**Comment by ReinerNippes** [comment]
the error message says the inventory can't be parsed as yaml. thats true because it's an ini file.
to you use another ansible.cfg where inventory ini parsing is disabled?
