### ISSUE TITLE
Support for Fedora

### ISSUE THREAD

**Issue by ebdavison** [ReinerNippes/nextcloud#47]
Would be good to add support for Fedora to this script.  I have Fedora 30 and would like to use this to do the NextCloud on my system but Fedora is not currently in the scripts.
What would it take to add this support.  Should be very similar to CentOS with some updated packages names.  Yum still works as an alias for dnf so no change needed there.

**Comment by ReinerNippes** [comment]
it would probably take a weekend. 

but last time i started it ended up with a small ansible problem.
https://github.com/ansible/ansible/issues/60730

if you want to try yourself: 
`grep -r CentOS *` will list you all files where this os specific variables is used. Just edit all of them and copy the line into `Fedora: ....` 
next
`find . -name CentOS.yml` will find all files with os specific tasks. Copy the file. And hope that Fedora and CentOS are compatible. But probably you have to add different yum repo for Fedora than CentOS. 
You 'll find out by running the playbook again and again. And fix all errors.

**Comment by ebdavison** [comment]
OK, I will see how far I can get.

**Comment by ReinerNippes** [comment]
so i created a new branch `fedora` for testing. 

problem: php-fpm is not starting. 
```
sudo systemctl start php-fpm
Failed to start php-fpm.service: Unit tmp.mount is masked.
```
@ebdavison any idea?

**Comment by ebdavison** [comment]
Yes, see #48 for my report and handling.  That report is on CentOS but should be the same for Fedora as they both ship with SELinux enabled.

**Comment by ebdavison** [comment]
Thanks for the branch.  Seems you have gotten further along than I have so far.  I have both a Fedora 30 box and a Centos 7 box that needs this so am working through the CentOS install right now.

**Comment by ReinerNippes** [comment]
if you start the playbook right with
```
./nextcloud.yml -e 'ansible_python_interpreter=/usr/bin/python3'
```
and unmask the tmp.mount service (for whatever reason it's masked i don't know)
```
sudo systemctl unmask tmp.mount
```

one will run into a ansible problem. it seems.

```
TASK [prep_nextcloud : nextcloud cronjob] *******************************************************************************************************************************
Monday 26 August 2019  15:25:54 +0000 (0:00:02.023)       0:02:58.915 *********
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    /home/ec2-user/.ansible/tmp/ansible-tmp-1566833154.49-58270406984110/AnsiballZ_cron.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    Traceback (most recent call last):
      File "/home/ec2-user/.ansible/tmp/ansible-tmp-1566833154.49-58270406984110/AnsiballZ_cron.py", line 114, in <module>
        _ansiballz_main()
      File "/home/ec2-user/.ansible/tmp/ansible-tmp-1566833154.49-58270406984110/AnsiballZ_cron.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ec2-user/.ansible/tmp/ansible-tmp-1566833154.49-58270406984110/AnsiballZ_cron.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/usr/lib64/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib64/python3.7/imp.py", line 169, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_cron_payload_1hl4_8bd/__main__.py", line 770, in <module>
      File "/tmp/ansible_cron_payload_1hl4_8bd/__main__.py", line 624, in main
      File "/tmp/ansible_cron_payload_1hl4_8bd/__main__.py", line 250, in __init__
      File "/tmp/ansible_cron_payload_1hl4_8bd/__main__.py", line 272, in read
    __main__.CronTabError: Unable to read crontab
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

@ebdavison what about using another os or run nextclud in a container?

**Comment by ReinerNippes** [comment]
the playbook should be ready now for fedora.

except: 
- no cron job added to roots crontab
- selinux enforced won't work.

**Comment by ReinerNippes** [comment]
did you `git fetch && git pull` ?

**Comment by ReinerNippes** [comment]
the 'dict object' for this task is defined here:

https://github.com/ReinerNippes/nextcloud/blob/ec5758e5c372a4330f2b29c318bdfb07c1fddaa2/group_vars/all.yml#L6

could you please look if you have this version of the file?

**Comment by ebdavison** [comment]
I have made progress on this; sorry for delay.  But even with the checkout current, I am finding quite a bit that I am having to adjust still for Fedora.  I will keep track of it all and send you along the way.

I have one though that I am stuck on ... (changed my domain name below to something non-identifying but rest is straight from error)

```
TASK [prep_nextcloud : set nextcloud domain config.php values] *********************************************************************************************************
Thursday 19 September 2019  23:26:43 -0500 (0:00:00.182)       0:07:30.883 **** 
failed: [localhost] (item={'key': 'overwrite.cli.url', 'value': '--value=https://hostname.example.com'}) => changed=true 
  ansible_loop_var: item
  cmd: php occ config:system:set overwrite.cli.url --value=https://hostname.example.com
  delta: '0:00:00.390557'
  end: '2019-09-19 23:26:44.502389'
  item:
    key: overwrite.cli.url
    value: --value=https://hostname.example.com
  msg: non-zero return code
  rc: 1
  start: '2019-09-19 23:26:44.111832'
  stderr: |2-
  
  
      There are no commands defined in the "config:system" namespace.
  stderr_lines: <omitted>
  stdout: Nextcloud is not installed - only a limited number of commands are available
  stdout_lines: <omitted>
failed: [localhost] (item={'key': 'trusted_domains', 'value': '1 --value=hostname.example.com'}) => changed=true 
  ansible_loop_var: item
  cmd: php occ config:system:set trusted_domains 1 --value=hostname.example.com
  delta: '0:00:00.393948'
  end: '2019-09-19 23:26:45.714061'
  item:
    key: trusted_domains
    value: 1 --value=hostname.example.com
  msg: non-zero return code
  rc: 1
  start: '2019-09-19 23:26:45.320113'
  stderr: |2-
  
  
      There are no commands defined in the "config:system" namespace.
  stderr_lines: <omitted>
  stdout: Nextcloud is not installed - only a limited number of commands are available
  stdout_lines: <omitted>

```

**Comment by ReinerNippes** [comment]
you may check your config/config.php . if it's exist but is nearly empty the initial install process didn't finish. in this case you can 
- remove config.php, the nextcloud database and the data folder to start over
or
- try to setup nextcloud manually via web gui or cli.

**Comment by ReinerNippes** [comment]
Merged into master
