### ISSUE TITLE
Centos 7.6.1810 - SELinux violation

### ISSUE THREAD

**Issue by ebdavison** [ReinerNippes/nextcloud#48]
In working through this ansible script, I received a failure on php-fpm when it tried to start:

```
Fatal error:  PHP Startup: apc_mmap: mmap failed: in Unknown on line 0
```

Tracking this down led to an SELinux violation.  To fix it I had to do the following:

```
ausearch -m avc -i -ts recent | audit2allow -a -M php-fpm
semodule -i php-fpm.pp
```

The above commands needed to be repeated twice on my system to catch all of the violations.  Once done, php-fpm starts as expected and the script continues.

**Comment by ReinerNippes** [comment]
i'm ausearch/audit2allow/semodule are not a valid solution with ansible playbook. 
i guess during the run of the play are no entries in the audit.log file to search.

i tried to fix the part of the playbook but couldn't get it working.

https://github.com/ReinerNippes/nextcloud/blob/0d59b4e412bb2fb4510703580c5c85f6dcb1858b/roles/prep_nextcloud/tasks/main.yml#L30

**Comment by ReinerNippes** [comment]
ansible shouldn't be the problem.

the selinux conf is set here:
https://github.com/ReinerNippes/nextcloud/blob/ad8daf53188c0399fbf8d53cd42a6f13390cb86f/roles/prep_nextcloud/tasks/main.yml#L30

according to the nextcloud manual:
https://docs.nextcloud.com/server/16/admin_manual/installation/selinux_configuration.html

**Comment by ReinerNippes** [comment]
@ebdavison you may try the latest version of the fedora branch. should be fixed there.
