### ISSUE TITLE
Ubuntu 18 error

### ISSUE THREAD

**Issue by UAnton** [ReinerNippes/nextcloud#51]
msg: 'An unhandled exception occurred while running the lookup plugin ''password''. Error was a <class ''ansible.errors.AnsibleError''>, original message: Unable to create local directories(/private/etc/nextcloud): [Errno 13] Permission denied: b''/private/etc/nextcloud''

**Comment by ReinerNippes** [comment]
@UAnton did you run the playbook with sudo?

**Comment by UAnton** [comment]
@ReinerNippes I'm run from my mac. I try with sudo and without. Now have one more error - 
fatal: [172.16.20.123]: FAILED! => {
    "msg": "'nc_web_port' is undefined"
}

**Comment by ReinerNippes** [comment]
i never tested the playbook on a remote server. the permission error should be fixed now. 
https://github.com/ReinerNippes/nextcloud/commit/3c3b172884c8bb99d69667818c67dc577fcd78c9

the variable nc_web_port is defined in the inventory. did you change it?
https://github.com/ReinerNippes/nextcloud/blob/3c3b172884c8bb99d69667818c67dc577fcd78c9/inventory#L28
