### ISSUE TITLE
Install with distant SQL/Redis host

### ISSUE THREAD

**Issue by acs-ferreira** [ReinerNippes/nextcloud#53]
Is it possible to pass a variable like 

`-e nc_db_type=''` (empty, so don't install anything locally) and 

```
 -e nc_db_host=my.distant.host \
 -e nc_db=nextcloud \
 -e nc_db_user=nextcloud \
 -e nc_db_passwd='my@passwd'
``` 
so it will install the database on the provided host/user/db?

**Comment by ReinerNippes** [comment]
Should work. (I've done that a long time ago. As far as I remember with AWS RDS mysql.)

But.
You have to provide the database type because it's needed for the initial nextcloud setup.
https://github.com/ReinerNippes/nextcloud/blob/17e46827486d6f032684fc592461fe4e848d90fc/roles/prep_nextcloud/tasks/main.yml#L56

The "switch" to install or not the database management system locally it `nc_db_host == localhost`
https://github.com/ReinerNippes/nextcloud/blob/17e46827486d6f032684fc592461fe4e848d90fc/nextcloud.yml#L13

**Comment by acs-ferreira** [comment]
Thanks! What about `redis`?

**Comment by ReinerNippes** [comment]
Hand made. May be. Not tested.

Edit: 
https://github.com/ReinerNippes/nextcloud/blob/17e46827486d6f032684fc592461fe4e848d90fc/roles/prep_nextcloud/defaults/config.json#L4

And remove:
https://github.com/ReinerNippes/nextcloud/blob/17e46827486d6f032684fc592461fe4e848d90fc/nextcloud.yml#L10

In a future version I shall add some variables to the inventory to control this.

**Comment by acs-ferreira** [comment]
> In a future version I shall add some variables to the inventory to control this.
Great!

**Comment by ReinerNippes** [comment]
No a big job. 
Only testing is more complicate, because I have setup a sql/redis server before.
I know: Just launch some more ec2s and run the playbook remote.

**Comment by acs-ferreira** [comment]
Sure :)
To define Postgre port...? Didn't found any doc sorry.

**Comment by ReinerNippes** [comment]
-e nc_db_host=my.distant.host:6543 ???

Indeed it's not documented: https://docs.nextcloud.com/server/17/admin_manual/configuration_server/occ_command.html#command-line-installation-label

btw: if you ever run the playbook without the '-e's you will a different installation. to make it idempotent put the values in the inventory. I only use '-e' not push any secrets to git while I'm developing.

**Comment by acs-ferreira** [comment]
Sure, just using `-e` now to run some tests on a couple of sandboxes :)

I let this open if you want to have the reminder about "...add some variables to the inventory to control this...".

Otherwise, feel free to close...and thanks again ;)

**Comment by ReinerNippes** [comment]
Did the port thing work?

**Comment by acs-ferreira** [comment]
I'll give a try to all these things in the next hours, i'll give total feedback. 😎

**Comment by acs-ferreira** [comment]
Well at this time i've tried the cloud-init script in the repo but i just have a lot of warnings, finishing by:

```
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/handlers/main.yml with yaml plugin: Parsed empty YAML file
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/handlers/main.yml with ini plugin: Invalid host pattern '---' supplied,
'---' is normally a sign this is a YAML file.
 [WARNING]: Unable to parse /home/user/nextcloud/roles/restic_backup/handlers/main.yml as an inventory source
 [WARNING]: Unable to parse /home/user/nextcloud/roles/restic_backup/handlers as an inventory source
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/tasks/main.yml with auto plugin: no root 'plugin' key found,
'/home/user/nextcloud/roles/restic_backup/tasks/main.yml' is not a valid YAML inventory plugin config file
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/tasks/main.yml with yaml plugin: YAML inventory has invalid structure,
it should be a dictionary, got: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/tasks/main.yml with ini plugin: Invalid host pattern '---' supplied,
'---' is normally a sign this is a YAML file.
 [WARNING]: Unable to parse /home/user/nextcloud/roles/restic_backup/tasks/main.yml as an inventory source
 [WARNING]: Unable to parse /home/user/nextcloud/roles/restic_backup/tasks as an inventory source
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/templates/backup_nextcloud.sh.j2 with script plugin: problem running
/home/user/nextcloud/roles/restic_backup/templates/backup_nextcloud.sh.j2 --list ([Errno 13] Permission denied)
 [WARNING]:  * Failed to parse /home/user/nextcloud/roles/restic_backup/templates/backup_nextcloud.sh.j2 with ini plugin:
/home/user/nextcloud/roles/restic_backup/templates/backup_nextcloud.sh.j2:7: Expected key=value host variable assignment, got: -e
 [WARNING]: Unable to parse /home/user/nextcloud/roles/restic_backup/templates/backup_nextcloud.sh.j2 as an inventory source
 [WARNING]: Unable to parse /home/user/nextcloud/roles/restic_backup/templates as an inventory source
 [WARNING]: Skipping 'restic_url' as this is not a valid group definition
 [WARNING]: Skipping 'restic_install_path' as this is not a valid group definition
 [WARNING]: Could not match supplied host pattern, ignoring: blur-gra5-1
ERROR! Specified hosts and/or --limit does not match any hosts
 [WARNING]: Unable to update repository. Continuing with (forced) run of playbook.

 [WARNING]:  * Failed to parse /home/user/nextcloud/inventory with yaml plugin: Syntax Error while loading YAML.   did not find expected
<document start>  The error appears to be in '/home/user/nextcloud/inventory': line 2, column 1, but may be elsewhere in the file depending on
the exact syntax problem.  The offending line appears to be:  [nextcloud] localhost ansible_connection = local ^ here
 [WARNING]:  * Failed to parse /home/user/nextcloud/inventory with ini plugin: /home/user/nextcloud/inventory:2: Expected key=value host
variable assignment, got: ansible_connection
 [WARNING]: Unable to parse /home/user/nextcloud/inventory as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
 [WARNING]: Could not match supplied host pattern, ignoring: blur-gra5-1

PLAY [install nextcloud] *****************************************************************************************************************************
skipping: no hosts matched
```

Full script was:
```

#cloud-config

users:
  - default

packages:
  - vim
  - mc
  - wget
  - curl

package_upgrade: true

system_info:
  default_user:
    name: userHere
    uid: 1000
    gecos: "cloud-init created default user"
    lock_passwd: True
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    home: /home/userHere
    shell: /bin/bash
    ssh-authorized-keys:
      - 'ssh-rsa ............'

runcmd:
  - curl -s https://raw.githubusercontent.com/ReinerNippes/nextcloud/master/prepare_system.sh | /bin/bash
  - HOME=/root ansible-pull --clean --force -d /root/nextcloud -i 'nextcloud' --checkout devel -U https://github.com/ReinerNippes/nextcloud.git nextcloud.yml -e dhparam_numbits=2048 -e fqdn=fqdn.example.com
```

**Comment by ReinerNippes** [comment]
1. you have to remove/disable this task if you run redis remote
https://github.com/ReinerNippes/nextcloud/blob/17e46827486d6f032684fc592461fe4e848d90fc/roles/prep_nextcloud/tasks/main.yml#L45
(disable: put a `  when: false` at the end.)

2. in the ansible pull line (as it was just an example. sorry.) there is a `--checkout devel` but no more devel branch. And I guess `-i localhost,` is also better. The -e you have to rewrite anyway.

**Comment by acs-ferreira** [comment]
I can confirm that all this works.
Just on more question, is it possible to run this playbook without SSL?

This can be useful for reverse proxies that manage all the SSL stuff.

**Comment by ReinerNippes** [comment]
1. Define ssl_certificate_type='none' so the two ssl roles won't be executed.
https://github.com/ReinerNippes/nextcloud/blob/c206e6b7610f696d327ed57af64ee9a7992b0f1b/nextcloud.yml#L15
2. Modify the nginx nextcloud.conf and remove the ssl server:
https://github.com/ReinerNippes/nextcloud/blob/c206e6b7610f696d327ed57af64ee9a7992b0f1b/roles/prep_nginx/templates/nextcloud.conf.j2#L13
I think this part of the docker config file could work
https://github.com/ReinerNippes/nextcloud_on_docker/blob/dd93e8ea9ce62dc4d08ba5ecc88cf3086797eb20/roles/docker_container/templates/nginx.conf.j2#L54 
3. You disable this task (" when: ssl_certificate_type != 'none' "  at the end or delete it)
https://github.com/ReinerNippes/nextcloud/blob/c206e6b7610f696d327ed57af64ee9a7992b0f1b/roles/prep_nginx/tasks/main.yml#L73

You may also look if the variable ssl_certificate_type is used somewhere else. The certs are also used by talk, onlyoffice and collabora. If you need this the modification of the nextcloud.conf file should be enough.

**Comment by acs-ferreira** [comment]
Thanks for all.
