### ISSUE TITLE
small beauty mistake

### ISSUE THREAD

**Issue by sgutermann** [ReinerNippes/nextcloud#57]
Running on a fresh Debian Stretch

TASK [prep_ufw : Configuring firewall] ****************************************************************************************************************************************************************************
Saturday 02 November 2019  22:54:33 +0100 (0:00:00.038)       0:00:14.131 ***** 
--- before: /etc/default/ufw
+++ after: /home/sgutermann/.ansible/tmp/ansible-local-20650j0h7ktyu/tmpdqe6e_2x/etc_default_ufw.j2
@@ -1,4 +1,4 @@
-# /etc/default/ufw
+# Ansible managed
 #
 
 # Set to yes to apply rules to support IPv6 (no means only IPv6 on loopback
@@ -41,5 +41,4 @@
 # nf_conntrack_pptp, nf_nat_pptp: PPTP over stateful firewall/NAT
 # nf_conntrack_ftp, nf_nat_ftp: active FTP support
 # nf_conntrack_tftp, nf_nat_tftp: TFTP support (server side)
-IPT_MODULES="nf_conntrack_ftp nf_nat_ftp nf_conntrack_netbios_ns"
-
+IPT_MODULES="nf_conntrack_ftp nf_nat_ftp nf_conntrack_netbios_ns"
**\ No newline at end of file**

#############################

no new line at end of file.

#############################

TASK [prep_os : disable transparent hugepages - copy service file] ************************************************************************************************************************************************
Saturday 02 November 2019  23:02:02 +0100 (0:00:00.852)       0:07:43.172 ***** 
--- before
+++ after: /home/sgutermann/Work/nextcloud/roles/prep_os/files/disable-transparent-huge-pages.service
@@ -0,0 +1,13 @@
+[Unit]
+Description=Disable Transparent Huge Pages
+DefaultDependencies=no
+After=sysinit.target local-fs.target
+Before=basic.target
+
+[Service]
+Type=oneshot
+ExecStart=/bin/sh -c '/bin/echo never > /sys/kernel/mm/transparent_hugepage/enabled'
+ExecStart=/bin/sh -c '/bin/echo never > /sys/kernel/mm/transparent_hugepage/defrag'
+
+[Install]
+WantedBy=basic.target
**\ No newline at end of file**

changed: [lansol.gutermann.info]

TASK [prep_os : enable service disable-transparent-hugepages] *****************************************************************************************************************************************************
Saturday 02 November 2019  23:02:05 +0100 (0:00:02.083)       0:07:45.255 ***** 
fatal: [lansol.gutermann.info]: FAILED! => changed=false 
  msg: |-
    Unable to start service disable-transparent-huge-pages.service: Job for disable-transparent-huge-pages.service failed because the control process exited with error code.
    See "systemctl status disable-transparent-huge-pages.service" and "journalctl -xe" for details.

###########################

here as well no new line

############################

the error above simply states that on Debian Stretch the directory does not exist

**Comment by ReinerNippes** [comment]
thanks. should be fixed.
