### ISSUE TITLE
Onlyoffice error install

### ISSUE THREAD

**Issue by consultorml** [ReinerNippes/nextcloud#58]
Hi, I have an issue on a fresh Debian 10 instance. The script run very well, with an only one error: Onlyoffice fail install. 

TASK [prep_onlyoffice : start a onlyoffice container] *************************************************************************************************************************************************************
Thursday 07 November 2019  11:46:19 +0000 (0:00:00.040)       0:07:31.606 ***** 
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on localhost''s Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named ssl_match_hostname'

**Comment by ReinerNippes** [comment]
you may look here: https://stackoverflow.com/questions/42695004/importerror-no-module-named-ssl-match-hostname-when-importing-the-docker-sdk-fo/51071841

or you start from scratch and try the nextcloud-reloaded branch. i think i fixed all the python pip trouble there. nevertheless both branches are not compatible. you may try but it's likely to break your system. just `git checkout nextcloud-reloaded` after the `git clone` .

**Comment by consultorml** [comment]
Thanks for the response. I tried the `reloaded` branch. The installation was succesfull without any errors. But when I been tried to open a document, fails the integration: "Error, downlaod failed". The docker container logs say:

>  at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
[2019-11-07T20:32:53.973] [ERROR] nodeJS - error downloadFile:url=https://domain.com/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjEwNCwidXNlcklkIjoibG1hcmlubyIsIm93bmVySWQiOiJsbWFyaW5vIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.jdll6n0CQS4fOfD0HpZ2mUFJHRi0QAQbqcUmfbytAPI;attempt=3;code:EPROTO;connect:null;(id=3139687156)
Error: write EPROTO 140158711277376:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:

**Comment by consultorml** [comment]
> you may look here: https://stackoverflow.com/questions/42695004/importerror-no-module-named-ssl-match-hostname-when-importing-the-docker-sdk-fo/51071841

It's works! For the record, if someone have the same issues, the solution I followed:

1. Once the installation finish, reinstall the python module
```
sudo pip uninstall backports.ssl-match-hostname
sudo apt-get install python-backports.ssl-match-hostname
```
2. Reinstall Onlyoffice, downloading the ansible file, and run on the nextcloud playbook directory
```
wget  https://github.com/ReinerNippes/nextcloud/blob/master/only_office.yml
ansible-playbook only_office.yml
```
