### ISSUE TITLE
Sorry: I'm back! error="apt cache update failed"

### ISSUE THREAD

**Issue by jcklpe** [ReinerNippes/nextcloud#60]
Hey, sorry to bother you again, but I have been encountering more and more problems with my nexcloud installation so I figured that it was time to just wipe the drive and start over. 

This time I installed Pop OS which is a variant of Ubuntu. 

I installed some command line tools, vscode, and hyperterminal, gnome tweaks, and a few gnome extensions but other than that everything is basically the same as a clean install. 

And when I run the nextcloud playbook I get a failure as such here:

```
TASK [prep_letsencrypt : Add an apt key by id from a keyserver] *****************************************************************************
Tuesday 03 December 2019  00:01:44 -0600 (0:00:00.063)       0:00:34.201 ****** 
ok: [localhost] => (item=7BF576066ADA65728FC7E70A8C47BE8E75BCA694)

TASK [prep_letsencrypt : add additional repos] **********************************************************************************************
Tuesday 03 December 2019  00:01:45 -0600 (0:00:00.498)       0:00:34.699 ****** 
fatal: [localhost]: FAILED! => changed=false 
  msg: apt cache update failed

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=65   changed=2    unreachable=0    failed=1    skipped=18   rescued=0    ignored=0  
```

Any clue on what might be the cause? It looks like it's some kind of letsencrypt issue.

**Comment by ReinerNippes** [comment]
My guess: The playbook adds a repository to your system according to the major release number of Ubuntu to your system. 

https://github.com/ReinerNippes/nextcloud/blob/fd0667543277d964388fc479323f3aa156989eff/roles/prep_letsencrypt/tasks/Ubuntu.yml#L13

If Pop OS doesn't use the same release numbers that won't work. You would have to find all line where `{{ ansible_distribution_release }}` is used an replace it with the `18`. If that's the corresponding Ubuntu release. 

You may check this by running `sudo apt update` on the cli. You should get an error message like `repo not found`.

**Comment by jcklpe** [comment]
@ReinerNippes Thank you for responding. Okay so I went in and I changed the `{{ansible_distribution_release}}` to `19` since that's the release for Pop OS and is supposed to correspond to the 19 release of Ubuntu. 

It did not work. 

Does it need the full 19.04 or whatever versioning numbers?

**Comment by ReinerNippes** [comment]
sorry. i made a mistake. i think it's not the number. it's the code name. look here:

http://ppa.launchpad.net/certbot/certbot/ubuntu/dists/

**Comment by jcklpe** [comment]
@ReinerNippes  ah cool yeah that makes sense. So Pop OS is version 19.10 which is tagged to Ubuntu 19.1o which is code named Eoan Ermine which I don't see there. Should I just do Disco Dingo? (I'm going to go ahead and try but figured I'd respond here in case you saw it before I got back with whether or not that worked)

**Comment by ReinerNippes** [comment]
if it's the same fun like with fedora: good luck. it's really a mess to mix distro packages. 
in fact docker was inventet to solve exactly the trouble. ;-)

**Comment by jcklpe** [comment]
It looks like actually my version of Pop is still 19.04 so replacing it with disco hasn't been an issue. 

I changed 19 out for disco and I got a lot farther. This time the only problem was with the only office docker. Which gave me this response:
```
TASK [prep_onlyoffice : start a onlyoffice container] ***************************************************************************************
Thursday 05 December 2019  19:08:55 -0600 (0:00:00.032)       0:06:18.137 ***** 
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on pop-os''s Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named ssl_match_hostname'
```

I'm doing more research on it now but it seems like it's something to do with python and docker. 

Here's some more info:
```
python --version
Python 2.7.17rc1
```
I think this is related to that bug we found back in August: https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

**Comment by jcklpe** [comment]
Okay now I'm hitting a really weird bug. 

I'm doing a reinstallation of Nextcloud for 2 reasons:

1. because I want to fix some persistent bugs that have been cropping up with my previous nextcloud installation 
2. my old installation of nextcloud was on my previous installation of linux and somehow due to some process of hacky installations etc, I ended up in a situation where my terminal emulator Hyper wouldn't work. I could get by using Gnome terminal but I really like the look and feel of Hyper so considering #1, it seemed like maybe it would be worthwhile to do a complete OS resinstallation and reboot of Nextcloud. 

But I just ran the ansible script.... and hyper has stopped working again. 

I noticed this a few days ago when I last tried to install nextcloud and I assumed that it was due to me installing an app called komorebi: https://github.com/zeit/hyper/issues/4033

But Hyper just stopped working and I didn't try to install hyper at all. Could perhaps something in the ansible script be breaking the ability for hyper to install? 

I could do a reinstallation of Linux again (and I still might) but I was curious if you'd ever heard of something like this?

I'm also wondering if maybe I should forgo the ansible script and try installing this manually on my own. I've learned a lot in the last year so perhaps it wouldn't be so hard?

I'm going to try the python3 symlink trick re quick to see if that changes anything. If nextcloud can install after I do that, then I'm going to reinstall Pop OS from scratch and try running this again, with the disco variable inserted. And then I'll see if it's broken hyper or not.

**Comment by jcklpe** [comment]
I'm going to close this issue because I have decided to just use a default Ubuntu installation for now. However, in the process of doing this installation I have found that using this method disables/prevents the use of the [[Hyper]](https://hyper.is/) terminal emulator which is a problem because I like using that hyper terminal.
