### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by mat-m** [ReinerNippes/nextcloud#64]
Hello,

Since python 2.7 is EOL now, do you plan to have prepare_system.sh use python 3 instead ?

**Comment by ReinerNippes** [comment]
Yes. Sure. Nevertheless I'll stay for the moment with the "official" python versions and packets of the underlying distro. I'm sure Ubuntu/Debian/CentOS will provide (security) updates to python2 for a while.

**Comment by ReinerNippes** [comment]
For Ubuntu/Debian I changed prepare_system.sh. So ansible runs with python 3. 

https://github.com/ReinerNippes/nextcloud/blob/nextcloud-reloaded/prepare_system.sh

But it's not fully tested. E.g the ansible prostgres modules aren't aware of pyton3 automatically. I had to define `ansible_python_interpreter` just for this tasks.

https://github.com/ReinerNippes/nextcloud/blob/ac5dead0ca92d5e20a7c38766bdce34060a502a3/roles/postgres/tasks/database.yml#L14

**Comment by ReinerNippes** [comment]
the [nextcloud_on_docker](https://github.com/ReinerNippes/nextcloud_on_docker) playbook is now switched to python 3. 

the branch [nextcloud-reloaded](https://github.com/ReinerNippes/nextcloud/tree/nextcloud-reloaded) of the [nextcloud](https://github.com/ReinerNippes/nextcloud/) playbook is work in progress. the version installing nginx should be ok. the apache installation is not fully tested yet. 

i'm closing the ticket. if you encounter problem feel free to open a new one.
