### ISSUE TITLE
How to install fonts to collabora

### ISSUE THREAD

**Issue by P-C-R** [ReinerNippes/nextcloud#69]
Hello,

whats the best way to install fonts?

Best

**Comment by ReinerNippes** [comment]
Depends which version of the playbook you used. 

I found a how to install fonts to collabora here: https://help.nextcloud.com/t/installing-new-fonts-in-collabora/22758

If you run the version from master branch collabora will run in a container and you have to modify the docker file or map a font folder from the host os into the container. You have to find out which folder are needed 

If you run the branch nextcloud-reloaded collabora is installed via OS packages and you can follow the how to directly.
