### ISSUE TITLE
Python 2.7 EoL & task hang

### ISSUE THREAD

**Issue by Darkknight33** [ReinerNippes/nextcloud#70]
Python 2.7 has been EoL on Jan 1. 

Got an error message related to this: https://github.com/docker/docker-py/issues/1502 had to install python-docker to get around the problem.

There is a command in prep_nextcloud main.yml: db:convert-filecache-bigint that requires a y/n response. It's causing the task to hang. Here is the output when run manually:

sudo -u www-data ./occ db:convert-filecache-bigint

Following columns will be updated:

* mounts.storage_id
* mounts.root_id
* mounts.mount_id

This can take up to hours, depending on the number of files in your instance!
Continue with the conversion (y/n)? [n]

Hope these are useful.

**Comment by ReinerNippes** [comment]
Python 2.7: On which Linux distro?

**Comment by ReinerNippes** [comment]
About task hang: You could simply try to add `--no-interaction`  to this line: 
https://github.com/ReinerNippes/nextcloud/blob/f317cd95a5356144e9c09e2971e7890dd098536c/roles/prep_nextcloud/tasks/main.yml#L125

I'll do this after testing.

**Comment by Darkknight33** [comment]
> Python 2.7: On which Linux distro?

All of them? https://github.com/python/devguide/pull/344 I suppose someone might be doing security patches, but if it's clearly not supported by the core python devs any more. It's probably time to update as v3 is already 12 years old. 

> About task hang: You could simply try to add `--no-interaction` to this line:
> https://github.com/ReinerNippes/nextcloud/blob/f317cd95a5356144e9c09e2971e7890dd098536c/roles/prep_nextcloud/tasks/main.yml#L125
> 
> I'll do this after testing.

I'll give this a shot myself.

**Comment by ReinerNippes** [comment]
Python: You may have a look at the [nextcloud-reloaded](https://github.com/ReinerNippes/nextcloud/tree/nextcloud-reloaded) branch. You'll find a lot of "python 3 support" commits. Everything works fine on Ubuntu/Debian. As far as I tested it. 

But when I run the playbook on CentOS/Fedora this didn't went well. The yum module doesn't work with python3. So I had to add this to all yum tasks.
https://github.com/ReinerNippes/nextcloud/blob/31bbb25dfb49fe969bce769bf4a5beae5556abb0/roles/os/tasks/yum.yml#L31
That would be OK. But there is no libselinux-python.rpm for python3. So all selinux related tasks will fail. And firewalld also fails. The "official" RedHat statment: We support Python2 as long as RedHat 7. Same applies to CentOS 7. If you want Python3 move to RHEL/CentOS 8. In CentOS 8 they removed docker support and renamed imagemagick. :-(

When I have time again I'll think about an elegant solution for CentOS7 and python3. 

Until then: Don't worry about python2. It's supported by the distro owner.

**Comment by Darkknight33** [comment]
I use Debian & Ubuntu, so that makes sense. Thanks for the suggestions.

**Comment by Darkknight33** [comment]
--no-interaction worked great:

TASK [prep_nextcloud : backup jobs, upgrade apps and database tuning] *********************************************************************************************************
Saturday 29 February 2020  08:46:15 -0500 (0:00:00.057)       0:10:01.671 *****
changed: [XXXXXXX] => (item=background:cron)
changed: [XXXXXXX] => (item=upgrade)
changed: [XXXXXXX] => (item=db:add-missing-indices)
changed: [XXXXXXX] => (item=db:convert-filecache-bigint --no-interaction)

TASK [prep_nextcloud : upgrade nextcloud] ******************************************
