### ISSUE TITLE
Importing keys from keyserver.ubuntu.com fails

### ISSUE THREAD

**Issue by 0xphk** [ReinerNippes/nextcloud#74]
First of all, thank you for this timesaving playbook.

Just for information, on a current installation of Ubuntu 18.04 Server the import of signing keys fails for the relevant tasks. As the manual import worked without problem, I was able to fix this by adding "hkps://" prefix to the keyserver.ubuntu.com addresses in the roles/tasks. 

May this could help others with the same problem.

**Comment by github-inedo** [comment]
Hello all
Just to confirm in the same context (fresh Ubuntu 18.04 Server, the given solution works
You save my day :)

**Comment by ReinerNippes** [comment]
Should be fixed.

**Comment by 0xphk** [comment]
Fixed, thank you

closing here
