### ISSUE TITLE
Issue Multiple instances with this playbook

### ISSUE THREAD

**Issue by asoral** [ReinerNippes/nextcloud#78]
Hi,
First of all, I am extremely thankful to you for the script. Runs perfectly fine with my Ubuntu 18.04 (I only tried this). However, when I re-run the same ./nextcloud.yml with different values in inventory file, it just doesn't start the new instance (different DNS, same IP, different port) but also crashes the first running container.

Is there something I am missing, Like **what all values** in **what all files** should I change before re-using this script to install another instance of nextcloud on the same server.

Please help

**Comment by ReinerNippes** [comment]
Sorry. I think it's easier to do this manually than to change the playbook. For example the path /var/www/html/nextcloud is too often hard coded in the tasks that is playbook.

If you just setup a plain vanilla nextcloud (without talk, fulltext search, only/collaboraoffice) you simply create another database, copy the /var/www/nextcloud folder, create another vserver by coping and editing /etc/nginx/config/nextcloud.conf and rerun certbot to create a new certificate. If you can use the redis instance I can't tell you. 

If you know ansible and want to go through please use the nextcloud-reloaded branch. In this branch I tried to make the playbook more modular. But it's still work in progress.
