### ISSUE TITLE
Collabora Problem

### ISSUE THREAD

**Issue by P-C-R** [ReinerNippes/nextcloud#79]
After a Nextcloud Update Collabor was broken.
i fixed it with adding these to the nextcloud.conf of nginx

 location ^~ /hosting/capabilities {
        proxy_pass https://localhost:9980;
        proxy_set_header Host $http_host;
    }

Source: https://help.nextcloud.com/t/collabora-problem-after-upgrade-to-3-6-0/81434/22

**Comment by ReinerNippes** [comment]
Thanks. I added this to the nginx config.
