### ISSUE TITLE
No package matching 'python-pip' is available

### ISSUE THREAD

**Issue by frankkkiiie** [ReinerNippes/nextcloud#80]
I get the error message; `No package matching 'python-pip' is available`.

Running `pip install -U pip` gives me;

`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in /home/administrator/.local/lib/python2.7/site-packages (20.1.1)
`

**Comment by ReinerNippes** [comment]
If you are on Ubuntu/Debian try the nextcloud-reloaded branch.

**Comment by frankkkiiie** [comment]
Seem to be running now with nextcloud-reloaded, thanks.

**Comment by frankkkiiie** [comment]
Giving me this error now;

```
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on Vault-381''s Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named ''distutils.spawn'''

```

**Comment by frankkkiiie** [comment]
Getting this now instead;

`TASK [check install status] *******************************************************************************************************************************************
Friday 12 June 2020  22:47:24 +0100 (0:00:00.056)       0:01:33.714 *********** 
fatal: [localhost]: FAILED! => changed=false 
  content: ''
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno -2] Name or service not known>'
  redirected: false
  status: -1
  url: https://nextcloud.example.tld/status.php

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=99   changed=10   unreachable=0    failed=1    skipped=62   rescued=0    ignored=0   
`

**Comment by ReinerNippes** [comment]
You didn't change the default url in the inventory.

So the playbook setup your nextcloud to listen to nextcloud.example.tld.

You have to edit the inventory and rerun the playbook. If you don't have an DNS entry you may use the up address of the server.

Maybe you have to edit config/config.php to change the server address there too.

**Comment by frankkkiiie** [comment]
That worked, thanks. Sorry, just very new to this.
