### ISSUE TITLE
The conditional check '( objectstore_s3_key != '' )' failed.

### ISSUE THREAD

**Issue by jcklpe** [ReinerNippes/nextcloud#84]
I decided to reinstall Nextcloud from scratch on my machine. Sorry to bother again but I ran into one small problem.   
  
I commented out all the stuff related to Amazon s3 because I am not backing stuff up to a third party cloud location nor am I backing stuff elsewhere. I'm just running NC off my desktop in my closet, and I don't have room for all the restic updates or s3 redundant storage etc. I know that's not ideal but it's my current means.   
  
So then, if I'm not going to use s3 etc what do I do about the parts the inventory related to it?  
  
Here's the full error message for context:  
```
TASK [nextcloud : check if config.php exists] ***********************************************************************************************
Wednesday 29 July 2020  04:24:50 -0500 (0:00:00.041)       0:02:11.711 ******** 
ok: [localhost]

TASK [nextcloud : define S3 as primary storage (only if config.php doesn't exist)] **********************************************************
Wednesday 29 July 2020  04:24:50 -0500 (0:00:00.172)       0:02:11.883 ******** 
fatal: [localhost]: FAILED! => 
  msg: |-
    The conditional check '( objectstore_s3_key != '' )' failed. The error was: error while evaluating conditional (( objectstore_s3_key != '' )): 'objectstore_s3_key' is undefined
  
    The error appears to be in '/home/aslan/nextcloud/roles/nextcloud/tasks/configure/nextcloud.yml': line 10, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: define S3 as primary storage (only if config.php doesn't exist)
      ^ here
```

**Comment by jcklpe** [comment]
I went into the nextcloud "roles" and commented out all the stuff related to s3.   
  
I also went and got rid of all the fail2ban stuff since it caused me problems last time. I think I've already accidentally hit the fail2ban limit though just in the process of running the install script a couple of times.

**Comment by ReinerNippes** [comment]
> I commented out all the stuff related to Amazon s3 because I am not backing stuff up to a third party cloud location nor am I backing stuff elsewhere. I'm just running NC off my desktop in my closet, and I don't have room for all the restic updates or s3 redundant storage etc. I know that's not ideal but it's my current means.

If you comment out a variable in athe inventory the playbook will fail.  as you can see the playbook checks if `objectstore_s3_key != ''`. But the complete playbooks fails if objectstore_s3_key is undefined. so leave `objectstore_s3_key = ''` in the inventory. 

Which branch you are using right now? master or nextcloud_reloaded?

**Comment by jcklpe** [comment]
@ReinerNippes It's actually working now!   
  
I read a lot of issue tickets dealing with 500 errors and most of the time people said they had to revert their default config files. So I went in, changed the name of config.php to config.old.php and then reran the nextcloud.yml file and after that, it worked!
