### ISSUE TITLE
The task includes an option with an undefined variable. 

### ISSUE THREAD

**Issue by daleosm** [ReinerNippes/nextcloud#87]
I'm trying to build your dev branch to see how it runs on AWS/Ubuntu 20.04. Please can you advise on the error I'm getting when installing elasticsearch. Line 22 is - "{{ elasticsearch_jdk_version[ansible_distribution]['v' + ansible_distribution_major_version] }}"

fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'v20'
  
    The error appears to be in '/home/ubuntu/nextcloud/roles/fulltextsearch/tasks/apt.yml': line 22, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: install elasticsearch packages
      ^ here

**Comment by ReinerNippes** [comment]
https://github.com/ReinerNippes/nextcloud/commit/2b3db2bebe0f4eb385c2f84d625600211575363d should fix this.

if another openjdk than v11 is needed let me know.

**Comment by daleosm** [comment]
Fixed. Thanks for your great work.
