### ISSUE TITLE
nextcloud-reloaded branch: ACME.sh fails during provisioning when host is IPv6 only

### ISSUE THREAD

**Issue by mfld-pub** [ReinerNippes/nextcloud#88]
Testing nextcloud-reloaded on Ubuntu 20.04.1 

Where host is dev.example.com and only has an AAAA dns entry pointing to 2001:db83:1234:5678::1

It will fail at the acme.sh step
```

TASK [tls-certificate : get certificates] ***************************************************************************************************************************************************************************************************
Saturday 19 September 2020  06:44:07 +0200 (0:00:00.029)       0:00:27.052 ****
fatal: [localhost]: FAILED! => changed=true
  cmd:
  - ./acme.sh
  - --issue
  - --home
  - /opt/acme/sh
  - --config-home
  - /opt/acme/sh/conf
  - --domain
  - dev.example.com
  - --keylength
  - ec-256
  - --cert-home
  - /opt/acme/sh/certs
  - --cert-file
  - /etc/ssl/private/dev.example.com/dev.example.com.crt
  - --key-file
  - /etc/ssl/private/dev.example.com/dev.example.com.key
  - --ca-file
  - /etc/ssl/private/dev.example.com/ca.crt
  - --fullchain-file
  - /etc/ssl/private/dev.example.com/fullchain.crt
  - --webroot
  - /var/www/letsencrypt
  - --reloadcmd
  - systemctl restart nginx
  delta: '0:00:07.122275'
  end: '2020-09-19 06:44:14.750375'
  failed_when_result: true
  msg: non-zero return code
  rc: 1
  start: '2020-09-19 06:44:07.628100'
  stderr: |-
    [Sat 19 Sep 2020 06:44:14 AM CEST] dev.example.com:Verify error:Fetching http://dev.example.com/.well-known/acme-challenge/RrbVs5H8YMAxm5bRI9sCisDW8rl6Giv5LMYPqflT91k: Connection refused
    [Sat 19 Sep 2020 06:44:14 AM CEST] Please add '--debug' or '--log' to check more details.
    [Sat 19 Sep 2020 06:44:14 AM CEST] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
  stderr_lines: <omitted>
  stdout: |-
    [Sat 19 Sep 2020 06:44:08 AM CEST] Using CA: https://acme-v02.api.letsencrypt.org/directory
    [Sat 19 Sep 2020 06:44:08 AM CEST] Single domain='dev.example.com'
    [Sat 19 Sep 2020 06:44:08 AM CEST] Getting domain auth token for each domain
    [Sat 19 Sep 2020 06:44:10 AM CEST] Getting webroot for domain='dev.example.com'
    [Sat 19 Sep 2020 06:44:10 AM CEST] Verifying: dev.example.com
  stdout_lines: <omitted>
```

If there is any interest in making IPv6 work I will take a look and see what ufw / nginx bits could be modified.

**Comment by ReinerNippes** [comment]
you may try to put `proto: ipv6` in this line

https://github.com/ReinerNippes/nextcloud/blob/2b3db2bebe0f4eb385c2f84d625600211575363d/roles/webserver/tasks/firewall_config.yml#L10

if you want to disable ufw in the playbook, comment out the following tasks:

https://github.com/ReinerNippes/nextcloud/blob/2b3db2bebe0f4eb385c2f84d625600211575363d/roles/os/tasks/main.yml#L8
https://github.com/ReinerNippes/nextcloud/blob/2b3db2bebe0f4eb385c2f84d625600211575363d/roles/webserver/tasks/main.yml#L29

maybe you have to grep for `ufw:` to find all tasks. 

and you may check if this jinja templating is working on your machine:

https://github.com/ReinerNippes/nextcloud/blob/2b3db2bebe0f4eb385c2f84d625600211575363d/roles/webserver/templates/nginx/nextcloud.conf.j2#L3

it should detect an ipv6 address and add this line (plus the one for ssl in line 19)

**Comment by mfld-pub** [comment]
Thank you! 

The playbook is pretty solid. Thanks for maintaining.
