### ISSUE TITLE
No Database-table-prefix option in NC20?

### ISSUE THREAD

**Issue by Baker0052** [ReinerNippes/nextcloud#89]
Fatal: [localhost]: FAILED! => changed=true
  cmd: |-
    php occ  maintenance:install  --database pgsql  --database-host "localhost"  --database-name nextcloud  --database-t
able-prefix oc_  --database-user nextcloud  --database-pass XXXXXXXXXXX  --admin-user admin  --admi
n-pass XXXXXXXXXXXXXX  --data-dir /var/nc-data
  delta: '0:00:00.468677'
  end: '2020-10-03 13:29:27.633935'
  msg: non-zero return code
  rc: 1
  start: '2020-10-03 13:29:27.165258'
  stderr: |2-

      The "--database-table-prefix" option does not exist.

    maintenance:install [--database DATABASE] [--database-name DATABASE-NAME] [--database-host DATABASE-HOST] [--databas
e-port DATABASE-PORT] [--database-user DATABASE-USER] [--database-pass [DATABASE-PASS]] [--database-table-space [DATABAS
E-TABLE-SPACE]] [--admin-user ADMIN-USER] [--admin-pass ADMIN-PASS] [--admin-email [ADMIN-EMAIL]] [--data-dir DATA-DIR]
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by ReinerNippes** [comment]
Yes. Sorry. Seem's someone dropped or changed that option. 
https://help.nextcloud.com/t/what-happens-to-database-table-prefix-in-nextcloud-20/93858 

According to which branch you are using edit or delete the following line:

nextcloud-reloaded: 
https://github.com/ReinerNippes/nextcloud/blob/2b3db2bebe0f4eb385c2f84d625600211575363d/roles/nextcloud/tasks/configure/nextcloud.yml#L38

master:
https://github.com/ReinerNippes/nextcloud/blob/479fa26651982c12bdb133937cf194598c71680c/roles/prep_nextcloud/tasks/main.yml#L59

or change the download url in the inventory to install NC19 (and upgrade later to NC20).

nextcloud-reloaded:
https://github.com/ReinerNippes/nextcloud/blob/2b3db2bebe0f4eb385c2f84d625600211575363d/inventory#L60

master:
https://github.com/ReinerNippes/nextcloud/blob/479fa26651982c12bdb133937cf194598c71680c/inventory#L69

the download url should be: https://download.nextcloud.com/server/releases/nextcloud-19.0.3.tar.bz2
