### ISSUE TITLE
Nextcloud-Reloaded Branch: Custom Domain Post Install

### ISSUE THREAD

**Issue by daleosm** [ReinerNippes/nextcloud#92]
Hello, would you mind advising on the procedure to add an additional custom domain post install? I have updated config.php and studied your code but I'm struggling with using ./acme.sh to save the certs in the right place and the correct way to update the files in /etc/nginx/conf.d

**Comment by ReinerNippes** [comment]
Hi Dale, could you please explain more what you mean by "additional custom domain post install"?

**Comment by daleosm** [comment]
Just needed to learn more from the nginx manual.
