### ISSUE TITLE
nextcloud-reloaded : Prepare system fails at Ansible upgrade on Debian Buster

### ISSUE THREAD

**Issue by alex-galey** [ReinerNippes/nextcloud#93]
On Debian Buster, from nextcloud reloaded branch, prepare system script failed at Ansible upgrade : 
Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is known to cause problems.

**Fix :** 
As explained by pip, I removed Ansible which was installed from apt and reinstalled from pip
```
sudo apt remove --purge ansible
sudo pip3 install ansible -U
```

**full error output :** 

Collecting ansible
  Using cached https://files.pythonhosted.org/packages/bb/09/dc8dee3f123166990bb4ca281001818fd552b4b5da56fa5cff2b47a0a0b4/ansible-2.10.1.tar.gz
    Complete output from command python setup.py egg_info:

                ### ERROR ###
    
                Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is
                known to cause problems.  Please uninstall the old version found at:
    
                /usr/lib/python3/dist-packages/ansible/__init__.py
    
                and install the new version:
    
                    pip uninstall ansible
                    pip install ansible
    
                If you have a broken installation, perhaps because ansible-base was installed before
                ansible was upgraded, try this to resolve it:
    
                    pip install --force-reinstall ansible ansible-base
    
                If ansible is installed in a different location than you will be installing it now
                (for example, if the old version is installed by a system package manager to
                /usr/lib/python3.8/site-packages/ansible but you are installing the new version into
                ~/.local/lib/python3.8/site-packages/ansible with `pip install --user ansible`)
                or you want to install anyways and cleanup any breakage afterwards, then you may set
                the ANSIBLE_SKIP_CONFLICT_CHECK environment variable to ignore this check:
    
                    ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install --user ansible
    
                ### END ERROR ###

**Comment by ReinerNippes** [comment]
Thanks. Should be fixed now.
